// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SGCarreras.Data;

#nullable disable

namespace SGCarreras.Migrations
{
    [DbContext(typeof(SGCarrerasContext))]
    [Migration("20251016224809_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("SGCarreras.Models.Carrera", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<int>("estado")
                        .HasColumnType("INTEGER");

                    b.Property<double>("kmTotales")
                        .HasColumnType("REAL");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ubicacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Carrera");
                });

            modelBuilder.Entity("SGCarreras.Models.Corredor", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<string>("cedula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nombreCompleto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("sexo")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Corredor");
                });

            modelBuilder.Entity("SGCarreras.Models.PuntoDeControl", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Carreraid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("distancia")
                        .HasColumnType("REAL");

                    b.HasKey("id");

                    b.HasIndex("Carreraid");

                    b.ToTable("PuntoDeControl");
                });

            modelBuilder.Entity("SGCarreras.Models.Registro", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Carreraid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Corredorid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("horaDeFinalizacion")
                        .HasColumnType("TEXT");

                    b.Property<int>("numeroEnCarrera")
                        .HasColumnType("INTEGER");

                    b.Property<int>("posicionEnCarrera")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("Carreraid");

                    b.HasIndex("Corredorid");

                    b.ToTable("Registro");
                });

            modelBuilder.Entity("SGCarreras.Models.TiempoParcial", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PuntoControlid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Registroid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("tiempo")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("PuntoControlid");

                    b.HasIndex("Registroid");

                    b.ToTable("TiempoParcial");
                });

            modelBuilder.Entity("SGCarreras.Models.PuntoDeControl", b =>
                {
                    b.HasOne("SGCarreras.Models.Carrera", "Carrera")
                        .WithMany("ptosDeControl")
                        .HasForeignKey("Carreraid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrera");
                });

            modelBuilder.Entity("SGCarreras.Models.Registro", b =>
                {
                    b.HasOne("SGCarreras.Models.Carrera", "Carrera")
                        .WithMany("registros")
                        .HasForeignKey("Carreraid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGCarreras.Models.Corredor", "Corredor")
                        .WithMany("registros")
                        .HasForeignKey("Corredorid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrera");

                    b.Navigation("Corredor");
                });

            modelBuilder.Entity("SGCarreras.Models.TiempoParcial", b =>
                {
                    b.HasOne("SGCarreras.Models.PuntoDeControl", "PuntoControl")
                        .WithMany()
                        .HasForeignKey("PuntoControlid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGCarreras.Models.Registro", "Registro")
                        .WithMany("TiemposParciales")
                        .HasForeignKey("Registroid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PuntoControl");

                    b.Navigation("Registro");
                });

            modelBuilder.Entity("SGCarreras.Models.Carrera", b =>
                {
                    b.Navigation("ptosDeControl");

                    b.Navigation("registros");
                });

            modelBuilder.Entity("SGCarreras.Models.Corredor", b =>
                {
                    b.Navigation("registros");
                });

            modelBuilder.Entity("SGCarreras.Models.Registro", b =>
                {
                    b.Navigation("TiemposParciales");
                });
#pragma warning restore 612, 618
        }
    }
}
